/**
 * This constant is used as a prefix for IDs that are generated by the IndexedDB hook. 
 * It helps to distinguish between IDs that are generated by the hook and those that are not.
 */
export const ID_UUID_PREFIX = "idb-";