import { ID_REGEX } from "../constants/ID_REGEX";
import { ID_UUID_PREFIX } from "../constants/ID_UUID_PREFIX";

/**
 * Checks if the given ID was generated by `generateLocalId()`.
 * @param id The ID to check.
 * @param prefix Optional prefix of the ID.
 * @returns {boolean} true if the ID was generated locally, otherwise false.
 */
export function isLocalId(id: string, prefix?: string) {
  const isUUID = (id: string) => ID_REGEX.test(id);
  const prefixToUse = typeof prefix === "string" ? prefix : ID_UUID_PREFIX;
  return (
    id.startsWith(`${prefixToUse}`) &&
    isUUID(id.replace(new RegExp(`^${prefixToUse}`), ""))
  );
}
