import { ID_REGEX } from "../constants/ID_REGEX";
import { ID_UUID_PREFIX } from "../constants/ID_UUID_PREFIX";

/**
 * Checks if the given ID was generated by `generateLocalId()`.
 * @param id The ID to check.
 * @param prefix Optional prefix of the ID.
 * @returns {boolean} true if the ID was generated locally, otherwise false.
 */
export function isLocalId(id: string, prefix?: string) {
  const prefixToUse = typeof prefix === "string" ? prefix : ID_UUID_PREFIX;
  if (!id.startsWith(prefixToUse)) return false;
  const uuidPart = id.slice(prefixToUse.length);
  return ID_REGEX.test(uuidPart);
}
